export const assetMovList= [
  {
    id: 1,
    title: 'Search Trans.',
    link: '/assetMovement/searchTransactions',
    imgSrc: '/icons/menu_icons/searchdoc.png',
    headerTitle: 'Search Document',
  },
  {
    id: 2,
    title: 'Maintenance',
    link: '/assetMovement/pages/maintenancePage',
    imgSrc: '/icons/menu_icons/maintenance.png',
    headerTitle: 'Maintenance',
  },
  {
    id: 3,
    title: 'Job Order',
    link: '/assetMovement/pages/JOFormPage',
    imgSrc: '/icons/menu_icons/joborder.png',
    headerTitle: 'Job Order Form',
  },
  {
    id: 4,
    title: 'Transfer',
    link: '/assetMovement/pages/TRFormPage',
    imgSrc: '/icons/menu_icons/transfer.png',
    headerTitle: 'Asset Transfer',
  },
  {
    id: 5,
    title: 'Disposal',
    link: '/assetMovement/pages/ADFormPage',
    imgSrc: '/icons/menu_icons/disposal.png',
    headerTitle: 'Asset Disposal',
  },
  {
    id: 6,
    title: 'Accountability',
    link: '/assetMovement/pages/AAFormPage',
    imgSrc: '/icons/menu_icons/acquisition.png',
    headerTitle: 'Asset Acquisition',
  },
  {
    id: 7,
    title: 'Lost Asset',
    link: '/assetMovement/pages/ALFormPage',
    imgSrc: '/icons/menu_icons/lostItems.png',
    headerTitle: 'Retiremnent by Sale',
  },
]